FROM python:3.11-slim

WORKDIR /app

COPY scripts/dashboard.py .
COPY requirements.txt .
COPY .env .
COPY scripts/ scripts/

RUN pip install --no-cache-dir --default-timeout=300 -r requirements.txt

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]